### PR TITLE
res.end not displaying on 2nd line

### PR DESCRIPTION
**Pull request by eltonnakagawa**
Not sure why res.end doesn't display on 2 lines.  Is it supposed to be only on one line?

### CODE REVIEW

**Comment by debasisb** [comment]
Not exactly sure but it is possible that res.end can be invoked once.

**Comment by debasisb** [comment]
Elton, res.end ends the response. Try to use res.send with a string.

**Comment by eltonnakagawa** [comment]
fixed it.  I had to use res.write with a res.end to add 2 lines.

**Comment by debasisb** [comment]
Glad you figured it out - res.write is the simple way and res.send also does similar.

**Pull request closed without merging**
